### ISSUE TITLE
Reuse django-auth-kerberos

### ISSUE THREAD

**Issue by okainov** [kiwitcms/python-social-auth-kerberos#1]
Just tried and seems that creating AuthBacked as child of existing KrbBackend from https://github.com/02strich/django-auth-kerberos is more efficient than using the current code.

At least, it was working for me without any issues :)

**Comment by atodorov** [comment]
django-auth-kerberos requires the user to add their username/password in a form which isn't the best idea when you are using SSO solution. I've converted this repository into a kerberos backend for Python Social Auth.

It does work for me but the quality is still Beta since I don't see an easy way to enable automated testing for kerberos negotiation.

If you decide to use this module it is available on PyPI. Let us know how it works for you but be prepared to open pull requests if something doesn't really work.

**Comment by okainov** [comment]
> django-auth-kerberos requires the user to add their username/password

Which is perfectly fine for our organization, since we can just check the password and do not store it. We use if for several months already with no issues
